language: node_js
node_js:
  - "node"
sudo: required
addons:
  firefox: "51.0"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
before_install:
  - export DISPLAY=:99.0
before_script:
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c "webdriver-manager start 2>&1 &";
  - cd src/Unosquare.Tubular2.Web
  - npm install
script:
  - gulp build
  - cd ../..
  - npm run test-once
  - npm run e2e
