language: node_js
node_js:
  - stable
sudo: false
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
before_script:
  - sh -e /etc/init.d/xvfb start
  - cd src/Unosquare.Tubular2.Web
  - npm install
script:
  - gulp build
  - npm run e2e
